### ISSUE TITLE
Disciplinas eletivas sem pré-requisitos ficam superestimadas

### ISSUE THREAD

**Issue by rochabm** [jairofsouza/EstimarOfertaVagas#5]

**Comment by jairofsouza** [comment]
Concordo com a issue. @rochabm você possui alguma ideia de como resolver esse problema?

**Comment by rochabm** [comment]
Eu tinha pensado, mas não postei pra não tumultuar. =)

A ideia era definir algo tipo "qual o período do aluno?". P. ex, se o menor período que ele ainda deve disciplinas é o 3o. Então, define ele como sendo "aluno do 3o P". Se uma disciplina eletiva MUITO na frente da grande, digamos do 8P, não tem pré-requisito, então não contar vaga para esse cara nela. 

Já deve ajudar a abaixar a demanda dessas disciplinas.

**Comment by jairofsouza** [comment]
OK, parece uma boa solução. Está relacionado com a issue #3.
